name: Auto Release

on:
  schedule:
    - cron: "0 0 1 * *"  # Runs on the 1st of every month
  workflow_dispatch:  # Allows manual triggering

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Get latest commit messages
        id: commits
        run: echo "commits=$(git log --pretty=format:'- %s' -n 10)" >> $GITHUB_ENV

      - name: Update CHANGELOG.md
        run: |
          echo "## Release ${{ env.date }}" > tmpfile
          echo "" >> tmpfile
          echo "${{ env.commits }}" >> tmpfile
          echo "" >> tmpfile
          cat CHANGELOG.md >> tmpfile || true
          mv tmpfile CHANGELOG.md

      - name: Commit and push CHANGELOG.md
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add CHANGELOG.md
          git commit -m "chore(release): update CHANGELOG for ${{ env.date }}"
          git push

      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "release-${{ env.date }}"
          name: "Release ${{ env.date }}"
          body_path: "CHANGELOG.md"
          draft: false
          prerelease: false
